// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cc736b63-33f1-427e-9960-59d92c46f9c2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_OLIBPgb0c",
    "aws_user_pools_web_client_id": "4kn56be7jpkke2lm6kjqgijf5g",
    "oauth": {},
    "aws_user_files_s3_bucket": "aarete-ocrwebapp-test",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_content_delivery_bucket": "aarete-ocr-webapp-test",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://aarete-ocr-webapp-test.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
