// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "aarete-ocr-webapp-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://aarete-ocr-webapp-dev.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:5aa323df-8619-491a-9e9c-3c0621ddffd1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_B9Go5OZBv",
    "aws_user_pools_web_client_id": "70ea1b05rfnj266csm536g5k61",
    "oauth": {},
    "aws_user_files_s3_bucket": "aarete-ocr-documentswebapp-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
