// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1e25c3a1-11b7-41e4-861e-cbbe90166a6d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_HsauGgUCH",
    "aws_user_pools_web_client_id": "3rj5ae9hc9r1iujh4pn2tpsf9s",
    "oauth": {},
    "aws_user_files_s3_bucket": "aarete-ocr",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_content_delivery_bucket": "ocr-amplify-webapp-20200116002434-hostingbucket-devv",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://ocr-amplify-webapp-20200116002434-hostingbucket-devv.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
