// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d11b2c6a-cdfe-4dab-bcfe-0bd29fdb5cbc",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_QcRJXrTJ3",
    "aws_user_pools_web_client_id": "72k2g2iai1q4oi89ucl7fsl83q",
    "oauth": {},
    "aws_user_files_s3_bucket": "aarete-ocrdevv-devv",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_content_delivery_bucket": "ocr-amplify-webapp-20200116002434-hostingbucket-devv",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://ocr-amplify-webapp-20200116002434-hostingbucket-devv.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
