/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:657b1f23-f3e2-4f49-a432-24284e6d5908",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_hyf3M416D",
    "aws_user_pools_web_client_id": "6i96u7h3p29stikqvcl4jd40i8",
    "oauth": {},
    "aws_user_files_s3_bucket": "aarete-ocr",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_content_delivery_bucket": "ocr-amplify-webapp-20200127095236-hostingbucket-master",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://ocr-amplify-webapp-20200127095236-hostingbucket-master.s3-website-us-east-1.amazonaws.com",
    "aws_cloud_logic_custom": [
        {
            "name": "admin",
            "endpoint": "https://0w2plgrb82.execute-api.us-east-1.amazonaws.com/master",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
